# Generated by Django 4.1.2 on 2022-11-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neonatal_information', models.CharField(max_length=250, null=True)),
                ('clinical_information', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neonatal_information', models.CharField(max_length=250, null=True)),
                ('clinical_information', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('password2', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('child_name', models.CharField(max_length=30, null=True)),
                ('child_date_of_birth', models.DateField()),
                ('registration_date', models.DateField()),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
