# Generated by Django 4.1.2 on 2022-11-08 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neonatal_information', models.CharField(max_length=250, null=True)),
                ('clinical_information', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neonatal_information', models.CharField(max_length=250, null=True)),
                ('clinical_information', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=250, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, null=True)),
                ('Phone_number', models.CharField(max_length=15, null=True)),
                ('child_name', models.CharField(max_length=30, null=True)),
                ('child_date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
