# Generated by Django 4.1.2 on 2022-10-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mothers',
            new_name='Mother',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='tittle',
            new_name='title',
        ),
    ]
