# Generated by Django 4.1.2 on 2022-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='child_date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
