# Generated by Django 4.1.2 on 2022-11-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
