# Generated by Django 4.1.2 on 2022-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
