# Generated by Django 4.1.2 on 2022-11-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0002_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('password2', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
