# Generated by Django 4.1.2 on 2022-10-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0002_rename_mothers_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
