# Generated by Django 4.1.2 on 2022-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0002_alter_message_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
