# Generated by Django 4.1.2 on 2022-10-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0003_alter_notification_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
