# Generated by Django 4.1.2 on 2022-11-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0003_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_number',
            name='name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
