# Generated by Django 4.1.2 on 2022-10-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0004_alter_notification_message_alter_notification_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neonatal_information', models.CharField(max_length=250)),
                ('clinical_information', models.CharField(max_length=250)),
            ],
        ),
    ]
