# Generated by Django 4.1.2 on 2022-11-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0004_contact_number_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_number',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
