# Generated by Django 4.1.2 on 2022-11-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0005_alter_contact_number_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='full_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
