# Generated by Django 4.1.2 on 2022-10-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('child_name', models.CharField(max_length=30)),
                ('child_date_of_birth', models.DateField()),
                ('registration_date', models.DateField()),
                ('appointment_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mother',
        ),
    ]
