# Generated by Django 4.1.2 on 2022-11-01 07:21

from django.db import migrations, models
import nuru.models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0006_users_delete_mother'),
    ]

   
