# Generated by Django 4.1.2 on 2022-11-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0006_message_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='full_name',
            new_name='Full_name',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_name', to='nuru.users'),
        ),
    ]
