# Generated by Django 4.1.2 on 2022-11-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0007_alter_users_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
    ]
