# Generated by Django 4.1.2 on 2022-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0007_rename_full_name_users_full_name_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='appointment_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='child_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
