# Generated by Django 4.1.2 on 2022-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0008_remove_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
