# Generated by Django 4.1.2 on 2022-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0009_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
