# Generated by Django 4.1.2 on 2022-11-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuru', '0011_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
